meta:
  url:
  title:
  thumbnail:
  description:
  sns:
    - twitter
slide:
  loop: false
  sidebar: false
  targetBlank: true
  showIndex: true
  isVertical: false
  chart: false
  math: false
extends:
  js:
  css: style.css
